package:
  name: gendef
  version: {{ GIT_DESCRIBE_TAG }}.r{{ GIT_DESCRIBE_NUMBER }}.g{{ GIT_DESCRIBE_HASH }}

source:
  git_url: https://github.com/mingw-w64/mingw-w64
  git_rev: dc42231f0

build:
  number: 0
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - ${PREFIX}/bin/gendef --help

about:
  home: https://github.com/mingw-w64/mingw-64
  summary: 'Generate list of exported symbols from a Portable Executable.'
  license: MIT AND GPL-3.0-or-later
  license_file:
    - mingw-w64-libraries/libmangle/COPYING
    - mingw-w64-tools/gendef/COPYING

extra:
  recipe-maintainers:
    - isuruf
