build_platform:
  win_64: linux_64
conda_build:
  error_overlinking: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  linux_s390x: azure
test: native_and_emulated
